/**
 * Generated by hddsgen v0.2.0
 * DO NOT EDIT
 *
 * TypeScript types with CDR2 serialization
 */

// CDR2 Serialization Helpers
export class Cdr2Buffer {
  private view: DataView;
  private offset: number = 0;
  private readonly littleEndian: boolean = true;

  constructor(buffer: ArrayBuffer | Uint8Array, offset: number = 0) {
    if (buffer instanceof Uint8Array) {
      this.view = new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);
    } else {
      this.view = new DataView(buffer);
    }
    this.offset = offset;
  }

  get position(): number { return this.offset; }
  set position(v: number) { this.offset = v; }

  /** Get the encoded bytes (from start to current position) */
  toBytes(): Uint8Array {
    return new Uint8Array(this.view.buffer, this.view.byteOffset, this.offset);
  }

  readUint8(): number { const v = this.view.getUint8(this.offset); this.offset += 1; return v; }
  readInt8(): number { const v = this.view.getInt8(this.offset); this.offset += 1; return v; }
  readUint16(): number { const v = this.view.getUint16(this.offset, this.littleEndian); this.offset += 2; return v; }
  readInt16(): number { const v = this.view.getInt16(this.offset, this.littleEndian); this.offset += 2; return v; }
  readUint32(): number { const v = this.view.getUint32(this.offset, this.littleEndian); this.offset += 4; return v; }
  readInt32(): number { const v = this.view.getInt32(this.offset, this.littleEndian); this.offset += 4; return v; }
  readFloat32(): number { const v = this.view.getFloat32(this.offset, this.littleEndian); this.offset += 4; return v; }
  readFloat64(): number { const v = this.view.getFloat64(this.offset, this.littleEndian); this.offset += 8; return v; }
  readBigUint64(): bigint { const v = this.view.getBigUint64(this.offset, this.littleEndian); this.offset += 8; return v; }
  readBigInt64(): bigint { const v = this.view.getBigInt64(this.offset, this.littleEndian); this.offset += 8; return v; }
  readBoolean(): boolean { return this.readUint8() !== 0; }

  readString(): string {
    const len = this.readUint32(); // CDR2: length includes null terminator
    const bytes = new Uint8Array(this.view.buffer, this.view.byteOffset + this.offset, len > 0 ? len - 1 : 0);
    this.offset += len; // advance past string + null
    return new TextDecoder().decode(bytes);
  }

  writeUint8(v: number): void { this.view.setUint8(this.offset, v); this.offset += 1; }
  writeInt8(v: number): void { this.view.setInt8(this.offset, v); this.offset += 1; }
  writeUint16(v: number): void { this.view.setUint16(this.offset, v, this.littleEndian); this.offset += 2; }
  writeInt16(v: number): void { this.view.setInt16(this.offset, v, this.littleEndian); this.offset += 2; }
  writeUint32(v: number): void { this.view.setUint32(this.offset, v, this.littleEndian); this.offset += 4; }
  writeInt32(v: number): void { this.view.setInt32(this.offset, v, this.littleEndian); this.offset += 4; }
  writeFloat32(v: number): void { this.view.setFloat32(this.offset, v, this.littleEndian); this.offset += 4; }
  writeFloat64(v: number): void { this.view.setFloat64(this.offset, v, this.littleEndian); this.offset += 8; }
  writeBigUint64(v: bigint): void { this.view.setBigUint64(this.offset, v, this.littleEndian); this.offset += 8; }
  writeBigInt64(v: bigint): void { this.view.setBigInt64(this.offset, v, this.littleEndian); this.offset += 8; }
  writeBoolean(v: boolean): void { this.writeUint8(v ? 1 : 0); }

  writeString(s: string): void {
    const bytes = new TextEncoder().encode(s);
    this.writeUint32(bytes.length + 1); // CDR2: length includes null terminator
    new Uint8Array(this.view.buffer, this.view.byteOffset + this.offset).set(bytes);
    this.offset += bytes.length;
    this.writeUint8(0); // null terminator
  }

  align(n: number): void {
    const padding = (n - (this.offset % n)) % n;
    this.offset += padding;
  }
}

// Module: aircp
export namespace aircp {
  export enum SenderType {
    AGENT = 0,
    USER = 1,
    SYSTEM = 2,
  }

  export function encodeSenderType(v: SenderType, buf: Cdr2Buffer): void {
    buf.writeUint32(v as number);
  }

  export function decodeSenderType(buf: Cdr2Buffer): SenderType {
    return buf.readUint32() as SenderType;
  }

  export enum MessageKind {
    CHAT = 0,
    CONTROL = 1,
    EVENT = 2,
    ERROR = 3,
  }

  export function encodeMessageKind(v: MessageKind, buf: Cdr2Buffer): void {
    buf.writeUint32(v as number);
  }

  export function decodeMessageKind(buf: Cdr2Buffer): MessageKind {
    return buf.readUint32() as MessageKind;
  }

  export interface Message {
    id: string;
    room: string;
    from_id: string;
    from_type: SenderType;
    to_agent_id: string;
    broadcast: boolean;
    kind: MessageKind;
    payload_json: string;
    timestamp_ns: bigint;
    protocol_version: string;
    room_seq: bigint;
    project: string;
  }

  export function encodeMessage(obj: Message, buf: Cdr2Buffer): void {
    buf.align(4);
    buf.writeString(obj.id);
    buf.align(4);
    buf.writeString(obj.room);
    buf.align(4);
    buf.writeString(obj.from_id);
    buf.align(4);
    encodeSenderType(obj.from_type, buf);
    buf.align(4);
    buf.writeString(obj.to_agent_id);
    buf.writeBoolean(obj.broadcast);
    buf.align(4);
    encodeMessageKind(obj.kind, buf);
    buf.align(4);
    buf.writeString(obj.payload_json);
    buf.align(8);
    buf.writeBigInt64(obj.timestamp_ns);
    buf.align(4);
    buf.writeString(obj.protocol_version);
    buf.align(8);
    buf.writeBigInt64(obj.room_seq);
    buf.align(4);
    buf.writeString(obj.project);
  }

  export function decodeMessage(buf: Cdr2Buffer): Message {
    const obj: any = {};
    buf.align(4);
    obj.id = buf.readString();
    buf.align(4);
    obj.room = buf.readString();
    buf.align(4);
    obj.from_id = buf.readString();
    buf.align(4);
    obj.from_type = decodeSenderType(buf);
    buf.align(4);
    obj.to_agent_id = buf.readString();
    obj.broadcast = buf.readBoolean();
    buf.align(4);
    obj.kind = decodeMessageKind(buf);
    buf.align(4);
    obj.payload_json = buf.readString();
    buf.align(8);
    obj.timestamp_ns = buf.readBigInt64();
    buf.align(4);
    obj.protocol_version = buf.readString();
    buf.align(8);
    obj.room_seq = buf.readBigInt64();
    buf.align(4);
    obj.project = buf.readString();
    return obj as Message;
  }

  /** Compute instance key hash from @key fields (FNV-1a, 16 bytes) */
  export function computeKeyMessage(obj: Message): Uint8Array {
    // FNV-1a hash of @key fields
    let hash = 14695981039346656037n;
    const PRIME = 1099511628211n;

    // Hash @key field: id
    const id_bytes = new TextEncoder().encode(obj.id);
    for (const b of id_bytes) {
      hash ^= BigInt(b);
      hash = (hash * PRIME) & 0xFFFFFFFFFFFFFFFFn;
    }

    for (const b of id_bytes) {
      hash ^= BigInt(b);
      hash = (hash * PRIME) & 0xFFFFFFFFFFFFFFFFn;
    }

    // Expand to 16 bytes
    const key = new Uint8Array(16);
    const keyView = new DataView(key.buffer);
    keyView.setBigUint64(0, hash, true);
    hash = (hash * PRIME) & 0xFFFFFFFFFFFFFFFFn;
    keyView.setBigUint64(8, hash, true);
    return key;
  }

}

